#!/bin/sh

# Pre-commit hook that rejects commit when a given regex is found in one of the files about to be committed.
# adapted from http://mark-story.com/posts/view/using-git-commit-hooks-to-prevent-stupid-mistakes

REGEX="console.log"

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # this is the root node, makes it work in a fresh repo, too.
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

for FILE in `git diff-index --name-status $against -- | cut -c3-` ; do
    if [ "`grep $REGEX $FILE`" ]
    then
        echo $FILE " contains '$REGEX'! "
        exit 1
    fi
done
exit 
